### PR TITLE
Add async (via Tokio) feature

### PR DESCRIPTION
**Pull request by SeanEClarke**
``Additional feature to enable async IO via teh tokio runtime.

Can be enabled by the addition of a standard feature flag in the Cargo.toml:

`clamav-client = { version = "0.2.2", features = ["asynch"]}`

Rather than create (yet another) clamav package, would you be open to contributions? if so I will update docs accordingly and push the updates for you to merge.

I have it all working in my environment, the only thing I am not too happy about is the module name, using `async` i.e. `clamav_client::async::ping` caused errors and required a delimiter, so it became  `clamav_client::r#async::ping`.

I am happy to change if `asynch` is not agreeable (`clamav_client::asynchronus` ?).

### CODE REVIEW

**Comment by toblux** [comment]
Thank you! Yes, I'm open to contributions. I will take a look in the next few days.

**Comment by SeanEClarke** [comment]
Great, I will update docs in this PR to reflect the changes etc.

**Comment by SeanEClarke** [comment]
I'd also like to expose an additional public function, a way t perform a scan from a Read trait as well as file or buffer - sort of like a stream through. I think you already do this in the private scan method. If you agree, I can do it in this PR or under another one.

suggestion is something like `scan_stream_tcp` which will just pass direct to the private `scan(Read, buffer, Write)` that allows flexibility to change the underlying implementation (which just by making the `scan` method public would prevent).

**Comment by toblux** [comment]
> If you agree, I can do it in this PR or under another one.

A separate PR would be better.

**Comment by toblux** [comment]
@SeanEClarke I'm not sure about the `Pin` requirement in `ping` and `scan` and would have used `Unpin` instead:

```rust
async fn ping<RW: AsyncRead + AsyncWrite + Unpin>(mut stream: RW) -> IoResult {
    ...
}

async fn scan<R: AsyncRead + Unpin, RW: AsyncRead + AsyncWrite + Unpin>(
    mut input: R,
    chunk_size: Option<usize>,
    mut stream: RW,
) -> IoResult {
    ...
}
```

Does your use case require pinning and could you elaborate on this? Thanks.

**Comment by SeanEClarke** [comment]
I "believe" Pin'ing is required to leverage the async read /write. I have an iterator to a store where objects are chunked, there is a custom Reader that wraps the iterator to the elements in the store and presents it as an AsyncRead trait (exposes it as a contiguous ::read(buf: &mut [u8])  which is passed through this method.

Happy to conceed its not needed, but just assumed it was.

update: I see your signature has them passed in by value and transfer ownership, my signature passed in a borrowed mutable reference.

**Comment by toblux** [comment]
@SeanEClarke Could you please test your use case with my latest commit? Thanks.

**Comment by SeanEClarke** [comment]
I have a few issues, but not related to that I think - so looks to be OK.

**Pull request merged**
